import "./globals.css";
import type { Metadata } from "next";
import ModalCart from "../../ui/modal/ModalCart";
import { Inter } from "next/font/google";
import { Navigation } from "../../ui/Navigation";
import Side from "../../ui/SideBar";
import { DataProvider } from "../store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CerqueTech Tienda Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation></Navigation>
        <Side></Side>
        <DataProvider>
          <ModalCart />
          {children}
        </DataProvider>
      </body>
    </html>
  );
}
